version: "2"

run:
  tests: true
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gosec
    - revive
    - errcheck
    - govet

  exclusions:
    rules:
      - linters:
          - revive
        path: pkg/template/
        text: "var-naming"

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gosec:
      excludes:
        - G306

formatters:
  enable:
    - gofmt
