version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm
    binary: "{{ .ProjectName }}"
    main: ./cmd/vt/main.go

  - id: darwin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    binary: "{{ .ProjectName }}"
    main: ./cmd/vt/main.go

partial:
  by: goos

archives:
  - formats:
      - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}
    files:
      - templates/

checksum:
  algorithm: sha256
  split: true
